### ISSUE TITLE
`BranchesApi#branch_compare` returns cloudfront error

### ISSUE THREAD

**Issue by bikezilla** [phrase/phrase-ruby#5]
Hello!

While playing with your gem (version 1.0.3 on ruby 2.7.0) I encountered the following error when trying to compare a branch:
```
irb(main):001:0> require 'phrase'
=> true
irb(main):002:0> PHRASE_PROJECT_ID = ***
irb(main):006:0> PHRASE_AUTH_KEY = ***
irb(main):007:0>
irb(main):008:1* Phrase.configure do |config|
irb(main):009:1*   config.api_key['Authorization'] = PHRASE_AUTH_KEY
irb(main):010:1*   config.api_key_prefix['Authorization'] = 'token'
irb(main):011:0> end
=> "token"
irb(main):012:0> branch = 'phrase-auto-pilot-2'
irb(main):013:0> Phrase::BranchesApi.new.branch_compare(PHRASE_PROJECT_ID, branch)
Traceback (most recent call last):
        7: from /Users/bikezilla/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
        6: from /Users/bikezilla/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        5: from /Users/bikezilla/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        4: from (irb):13
        3: from /Users/bikezilla/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/phrase-1.0.3/lib/phrase/api/branches_api.rb:18:in `branch_compare'
        2: from /Users/bikezilla/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/phrase-1.0.3/lib/phrase/api/branches_api.rb:72:in `branch_compare_with_http_info'
        1: from /Users/bikezilla/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/phrase-1.0.3/lib/phrase/api_client.rb:52:in `call_api'
Phrase::ApiError (Error message: the server returns an error)
HTTP status code: 403
Response headers: {"Content-Type"=>"text/html", "Transfer-Encoding"=>"chunked", "Connection"=>"keep-alive", "Date"=>"Fri, 09 Oct 2020 15:39:30 GMT", "Server"=>"nginx/1.15.9", "Vary"=>["Accept-Encoding", "Origin"], "X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "X-Rate-Limit-Limit"=>"1000", "X-Rate-Limit-Remaining"=>"995", "X-Rate-Limit-Reset"=>"1602258000", "Cache-Control"=>"no-cache", "Set-Cookie"=>["language=en; path=/; expires=Tue, 09 Oct 2040 15:39:30 GMT", "_phrase_session_sec=U2lGRUJPNFc3SUcyTkszbkhzZWJlWW5wOGZpWVVGUDdvNGk5RzlmbEtod29hZUp5T3Z5RFRpRjk0ZzM3SjhjaitXb2F0RVphbm5GdWJCSGdpVzJ0dEE9PS0tamRjSlJ6UVU5ZXhRR2lMczExR0FuUT09--3e81ff31c9b790ef35ddac1ae47bcf6bd8224dbb; path=/; secure; HttpOnly"], "X-Generated"=>"2020-10-09T15:39:30+00:00", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "X-Cache"=>"Error from cloudfront", "Via"=>"1.1 2125e078e0211a418e353b9df974d88b.cloudfront.net (CloudFront)", "X-Amz-Cf-Pop"=>"DUB2-C1", "X-Amz-Cf-Id"=>"dShO9i4DdlTCiayGsB2FvVoa35qGRBWnI9bg604PNyryLk9YSLf-hQ=="}
Response body:
irb(main):014:0>
```

I was able to execute other command such as `branch_show` successfully.

**Comment by theSoenke** [comment]
Hi @bikezilla, I've not been able to reproduce this so far. Could you give this a test whether this appears or this was a temporary CloudFront error which has now been resolved? There have been some improvements to the compare endpoint recently which might solve this issue you've experienced

**Comment by theSoenke** [comment]
I'll close this as it should be resolved now by now
